### ISSUE TITLE
Small frontend findings

### ISSUE THREAD

**Issue by entnx-01** [seanmorley15/AdventureLog#200]
Small frontend things: 

- [x] The star rating is displayed as number input field when creating a new adventure. Is it possible to use the star selection at that point?

- [x] The description fiel is a textfield. In my Opinion a text area would make more sense. 
- [x] Edit 2: and now I am nitpicking, but dates (under Itinerary by Date) should be left-aligned, either center + left aligned, OR left side with some padding, but not center + center aligned. And the map should be centered, not left aligned (also imo). See wanderlog as an example. The details under it should have an indent, and then also left aligned.

- [x] Edit 3: line breaks/tabs in adventure description (or any text block/description) should be rendered on page

- [x] Edit 4: this one is a bit bigger, create a collection, set date to middle of the month to 1st week of another month, create adventure, select lodging, select the entire span of the trip. See that for some reason the last few days are missing the lodging even though it should have it.

Further ideas: 
1. What do you think about adding gps / gpx tracks to a adventure? 
2. What do you think about supporting different languages? ✅
3. What about adding comments or multi visits to an adventure. Or is it a new adventure every visit?

**Comment by seanmorley15** [comment]
These are all great ideas! I have added them to my tracker and will keep this issue posted with updates! Thanks a lot!

**Comment by seanmorley15** [comment]
Those first 2 things were just addressed in #240. I will keep this here because the other ideas are still good. Regarding localization,  I would need some help figuring out how to do that.
Hope you enjoy!

**Comment by Snuupy** [comment]
in addition to line breaks, tabs and spaces should also be displayed (I frequently list details under each section grouped by indentation)

**Comment by seanmorley15** [comment]
All set with these requests! They will be released with v0.7.1!
