### ISSUE TITLE
Unable to create Adventure after pressing Esc in the location chooser modal

### ISSUE THREAD

**Issue by tedski** [seanmorley15/AdventureLog#203]
### Observed behavior

If Esc is pressed with the location chooser open, the entire creation flow is canceled and attempts to create new planned or visited Adventures fail.

### Expected behavior

Pressing Esc in the location chooser should only close the location chooser.

### Steps to reproduce

1. Navigate to Adventures
2. Click the Plus icon to add a new Adventure
3. Click either Planned or Visited Adventure
4. Click Select Location
5. Press Esc
6. Observe the entire flow is canceled
7. Click the Plus icon to add new Adventure
8. Click either Planned or Visited Adventure
9. Observe no creation modal appears
10. Refresh the page
11. Repeat step 2-3
12. Observe creation modal now appears.

**Comment by seanmorley15** [comment]
I see how this is an issue, I was able to reproduce it. I will make sure this gets fixed!
Thanks

**Comment by seanmorley15** [comment]
I am actually in the process of completely re-making the create and edit modals for adventures, with this update, there is no more nested modals so this will not be an issue anymore. I tried to find a way to fix it in the meantime but the UI library makes nested modals so hard to work with.
Here is a sneak peak at the new design.
![image](https://github.com/user-attachments/assets/b89fa95d-4274-4e48-9d2d-1931cf54fd03)

I will keep this issue open for now just so other people can see this is being worked on, thanks for reporting this!

**Comment by seanmorley15** [comment]
Just released that update into main, this issue is no longer present!
Hope you enjoy!
