### ISSUE TITLE
images are not displayed

### ISSUE THREAD

**Issue by mariushosting** [seanmorley15/AdventureLog#206]
![unavailable images](https://github.com/user-attachments/assets/15ee2040-2182-45d5-a1fb-8eafc19a5a0b)
images are not displayed. 
Docker compose, nginx.conf file everything is in order.

What can be the cause?

**Comment by mariushosting** [comment]
![Screenshot 2024-08-16 16 55 40](https://github.com/user-attachments/assets/3f1abaca-de51-42bd-815e-dc38a8532e43)
Added the region data, Restarted the container... unfortunately all images all images is still not displayed. Also same for profile picture that I upload.

Here is my compose: https://docker.mariushosting.com/mariushosting/237f854d3eeb4c15b1bbd755b95438f0

**Comment by mariushosting** [comment]
Putting the nginx part under reverse proxy solved the issue :-)
![works](https://github.com/user-attachments/assets/18d542fe-8666-4459-a2f8-e100caee3083)

**Comment by seanmorley15** [comment]
That's great! I'm so glad to hear!

**Comment by mariushosting** [comment]
> That's great! I'm so glad to hear!

I will make a guide for this in the next hours on my website. Do you have any logo for the AdvenutreLog app so I can use im my images?
