### ISSUE TITLE
[HELP] Configuration for own reverse proxy like NPM or traefik

### ISSUE THREAD

**Issue by pkirsche** [seanmorley15/AdventureLog#207]
Hello and thanks for this great project. Exactly what I was looking for for years!
But unfortunately I have some troubles with the setup. I am using my own reverse proxy (traefik and/or npm) and I am really confused with the setup and the different ports of the back- and frontends.

Finally with a lot of try and error I got an instance running showing me the webinterface behind my reverse proxy. Therefore I disabled the nginx container which would lead to a double proxy setup I think.
But then I got into the following troubles:

I try to login with the default (haven't changed any credentials in my testsetup yet) with user and pass "admin".
Within the docker logs, I then see this line:

```
web-1     | []
web-1     | { user: null }
```

Within the login mask, there is no reaction other than that line.
The same behavior when I try to register a user. Then I even don't see anything in the logfile.

During startup of the containers I don't get any errors but for me it looks like a missing connection between front- and backend.

Has anyone running AdventureLog behind a reverse proxy or can anyone tell me, what's going on with the login issue?

Thanks :)

**Comment by tedski** [comment]
You'll still need the nginx container as it serves the static content.  See #234 for a working example of AdventureLog behind a Traefik reverse proxy with TLS enabled.  This is how I set it up based on the docker-compose.yaml in the repo.

**Comment by seanmorley15** [comment]
Merged the new Traefik docker compose file
