### ISSUE TITLE
Disable User Registration

### ISSUE THREAD

**Issue by mariushosting** [seanmorley15/AdventureLog#210]
There is any environment variables to disable user registration after I registered the first user?

**Comment by seanmorley15** [comment]
Yes, I just added that feature. Make sure you docker compose pull the latest image and in the backend set DISABLE_REGISTRATION = True

**Comment by seanmorley15** [comment]
I will still make it so the frontend gets rid of the signup button when this is set but for now it just disables it at the API level.

**Comment by mariushosting** [comment]
> DISABLE_REGISTRATION = True

Thank you so much!
