### ISSUE TITLE
Feature Request: Support for Start and End Dates for Adventures

### ISSUE THREAD

**Issue by PhiCoderX** [seanmorley15/AdventureLog#214]
Currently, only a single date can be assigned to an adventure. This works for one-day events but is limiting for multi-day activities like holidays or weekend trips. It would be helpful to allow users to enter both a start and end date for an adventure for better tracking of adventure duration.

**Comment by seanmorley15** [comment]
This is a great idea! I have added to my issue tracker. Thanks!
