### ISSUE TITLE
Link out of the box

### ISSUE THREAD

**Issue by mariushosting** [seanmorley15/AdventureLog#218]
Share link is out of the box :-)
![share this adventure](https://github.com/user-attachments/assets/62ce53f6-a337-4d4a-934d-808f0831cff3)

**Comment by seanmorley15** [comment]
Thanks for reporting this! I will be able to fix this one pretty quick, its added to my list!
Thanks so much for taking the time to use and help improve AdventureLog!

**Comment by seanmorley15** [comment]
All set! Fixed in #222
