### ISSUE TITLE
Any idea why there are 51 states in the US?

### ISSUE THREAD

**Issue by TheBig-O** [seanmorley15/AdventureLog#224]
There seems to be an issue with the world travel portion.  
I've counted each of the blocks in the world travel tab for the US and there are only 50. However, when I click each of the regions/states, the result is 51 of 50 regions visited?  

<img width="814" alt="image" src="https://github.com/user-attachments/assets/2bc0d35c-832c-47f7-b4f0-aafd9fc9e5c9">

**Comment by seanmorley15** [comment]
The latest commit #229 fixes this issue be preventing duplicate regions from being visited and just in case filtering them on the frontend. You may need to delete the duplicate on your instance but future duplicates will be blocked 👍🏻 
Sorry this happened and thanks for reporting!

**Comment by TheBig-O** [comment]
That fixed it! Thank you!
Great App. I've been looking for something that did this for some time.
