### ISSUE TITLE
Inconsistent date format

### ISSUE THREAD

**Issue by PhiCoderX** [seanmorley15/AdventureLog#227]
Selecting a date during creation of an adventure in done in the DD/MM/YYYY format:
<img width="331" alt="Screenshot 2024-08-17 at 11 23 58" src="https://github.com/user-attachments/assets/716bc3f9-e294-4b7c-a553-3974680762c4">
On the "My Adventures" page it is then displayed in MM/DD/YYYY format:
<img width="116" alt="Screenshot 2024-08-17 at 11 24 12" src="https://github.com/user-attachments/assets/03135ab1-e4c3-4c10-8d53-2663426f7d64">

Overall it would be nice to be able to select the format via a locale as my "native" format is DD.MM.YYYY

**Comment by seanmorley15** [comment]
Yes I agree, there is also a reported issue with time zone inconsistencies that I will fix along with this.
Thanks for reporting it!

**Comment by seanmorley15** [comment]
I just merged my fix into the main branch. I hope this helps:

- The time zone is now always UTC on the server for consistency
- Dates and times are now entered and displayed based on UTC on the frontend so they will stay the same as how they are entered
- Dates and times are now always displayed in your locale default
Let me know if I'm missing something!

**Comment by PhiCoderX** [comment]
Works perfect, thank you!
