### ISSUE TITLE
Access through Tailscale/Wireguard

### ISSUE THREAD

**Issue by NovaCyntax** [seanmorley15/AdventureLog#237]
Local access seems to be working fine, but how would you configure this to work through a private VPN and not a reverse proxy? The additional nginx container is throwing me for a loop.

Apologies if this is a silly question.

**Comment by seanmorley15** [comment]
I really am not familiar with using these but I would imagine that you would have to change around the ORIGIN and CSRF origins. I think that the extra nginx container will still be necessary though.
I will mark this as help wanted to see if someone who has experience with this can look at it!
Sorry about that

**Comment by NovaCyntax** [comment]
No problem! Appreciate the quick reply.

**Comment by tedski** [comment]
This will need a bit more information.  Do you plan to put the AdventureLog containers directly on your Tailnet or do you just want to be able to access them via advertised subnet routes?

**Comment by NovaCyntax** [comment]
I'd like to be able to visit "My.Tailscale.IP.Address:PORT" and use the application, with "PORT" being the port value assigned to the frontend.

**Comment by tedski** [comment]
I'm assuming what you're indicating is that the host that runs docker is on the Tailnet already.  With the current docker compose configurations, you would only need to add the url you're trying to access to the CSRF_TRUSTED_ORIGINS environment variable on the backend container.  Let's assume the docker host has an internal address of 192.168.1.128 and a tailscale ip of 100.128.64.64.  You'd probably want to access both over Tailscale and the LAN, so you would set `CSRF_TRUSTED_ORIGINS=http://192.168.1.128,http://100.128.64.64`.  I'd probably also add the fqdn with the Tailnet name to that list so you don't need to memorize IP addresses.

**Comment by NovaCyntax** [comment]
That works fine for accessing the frontend, but clicking "login" doesn't seem to do anything. I've cleared cache/cookies for the site in my browser settings as well.

For what it's worth, I only modified the CSRF_TRUSTED_ORIGINS variable, I did not change the FRONTEND_URL value.

**Comment by tedski** [comment]
It'd probably be best for you to share your config at this point.  You should obfuscate your IP addresses and any secrets.

**Comment by NovaCyntax** [comment]
```
version: "3.9"

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    environment:
      - PUBLIC_SERVER_URL=http://My.Local.IP.Address:8567/
      - ORIGIN=http://My.Local.IP.Address:8097
      - BODY_SIZE_LIMIT=Infinity
      - PGID=1000
      - PUID=1000
    ports:
      - "8097:3000"
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - /home/my-user/adventure-log/postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=thisisarandomsecret
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://127.0.0.1:81'
      - CSRF_TRUSTED_ORIGINS=http://My.Local.IP.Address:8097,http://My.Tailscale.IP.Address:8097,http://TailscaleHostName:8097
      - DEBUG=True
      - FRONTEND_URL='http://My.Local.IP.Address:8097'
    ports:
      - "8567:8000"
    depends_on:
      - db
    volumes:
      - /home/my-user/adventure-log/media:/code/media/

  nginx:
     image: nginx:latest
     ports:
       - "81:80" # Using port 81 to avoid conflict with your existing setup
     volumes:
       - /home/my-user/adventure-log/media:/app/media
       - /home/my-user/adventure-log/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     depends_on:
       - server

volumes:
  postgres_data:
  media:

```

Thank you, I appreciate the help!

**Comment by tedski** [comment]
Okay, a few changes to recommend and see where that gets us.

1. Change `PUBLIC_SERVER_URL` to `http://server:8567`
  This doesn't actually need to be publicly accessible -- it's poorly named.  This is the URL the frontend container uses to talk to the backend.  Docker handles this rather well already.  Docker Compose creates a network for all of the spec'd containers to reside in.  There's no need to route traffic outside of this network.  Docker also sets up dns names within these networks and those are more easily used than caring about IP addresses.  So, here we just give it the container name and the port that's specified.
1. Change `ORIGIN` to `http://My.Tailscale.IP.Address:8097`
  This environment variable is used by Svelte (the frontend framework) to determine what site was being requested.  For example, if we call /login, Svelte needs a way to know it was for http://adventurelog.example.com/login.  See the [Svelte docs](https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-hostheader-and-port-header) for more on that if you desire.
1. Change `PUBLIC_URL` to `http://My.Tailscale.IP.Address:81`
  This is the URL at which the nginx container is publicly accessible.  The backend container writes media files that are uploaded to it from the frontend via the API.  To read these URLs back, since the backend is not exposed directly, nginx serves these.  However, the backend needs to know how to tell the client which URL the file is accessible from.
1. [optional] Remove `ports` from the server spec.
  Since only the frontend container needs to talk to the backend server container and step 1 makes sure that all happens within the Docker network, then we don't need to expose any ports for the backend.  This is more about cleanliness than solving your issue, hence marking it as optional.

@seanmorley15 please read over my assertions and correct me if I'm wrong anywhere.

**Comment by NovaCyntax** [comment]
Thank you for the assistance and explanations! I made the suggested changes but am still experiencing the same issues when I click log in or sign up. Unfortunately, there are no log entries that appear from any of the containers associated with the stack.

**Comment by tedski** [comment]
Are there any errors in your browser console?

**Comment by NovaCyntax** [comment]
403 Forbidden

XHRPOST
http://My.Tailscale.IP.Address:8097/login
[HTTP/1.1 403 Forbidden 3ms]
message	"Cross-site POST form submissions are forbidden"

**Comment by tedski** [comment]
That is indicating that the issue is with the CSRF configuration for certain.  You're certain that the tailscale ip is in the CSRF_TRUSTED_ORIGINS env var?

**Comment by NovaCyntax** [comment]
Yes, I have the local IP address (which works fine), the Tailscale IP address (does not work), and the Tailscale device name "address" (does not work).

**Comment by seanmorley15** [comment]
"Cross-site POST form submissions are forbidden" means there is an issue with the ORIGIN variable in the frontend? Can you double check that?

**Comment by seanmorley15** [comment]
Also PUBLIC_SERVERURL=http://server:8000 is still what it should be due to docker networks using internal ports

**Comment by NovaCyntax** [comment]
The ORIGIN variable on my machine is the Tailscale IP address of the host machine, as recommended by @tedski

**Comment by seanmorley15** [comment]
Sorry if this is confusing, I don't know exactly how these types of vpns work but in general the ORIGIN needs to be the url the app is accessed from, this will prevent 403 errors from the frontend, if this is already set, there might be a difference that tailscale introduces
Hope this helps, if not hopefully someone else can chime in with their knowledge 🤞

**Comment by tedski** [comment]
Just to ensure I have all the context... your docker host is directly connected to your tailnet.  Your browser is on another machine that's also connected directly to the tailnet.  You are navigating to the tailnet IP address and/or the tailnet fqdn when you see the errors you pasted?

**Comment by NovaCyntax** [comment]
That is correct. I am trying to access the service (working!) and successfully log in (not working) to Adventure Log the same way I access my other services.

**Comment by tedski** [comment]
I'll spin up a test environment and see if I'm missing something.

**Comment by NovaCyntax** [comment]
Thanks a lot, I'm almost positive it's something on my end but I can't figure it out.

**Comment by tedski** [comment]
I am unable to reproduce the issue on my end.  Here's what I did:

* Spin up a fresh debian cloud instance
* Install git, tailscale, and the docker suite
* Connect the node to the tailnet using `tailscale up`
* Clone the AdventureLog repo
* Change `ORIGIN`, `CSRF_TRUSTED_ORIGINS`, and `FRONTEND_URL` to the node's tailscale ip address (from `tailscale ip -4` output)
* run `docker compose up -d`
* Connect my tailscale laptop to the tailnet
* Navigate to http://<tailscale ip>:8080
* Click login
* Login with admin:admin
* Success.

Here is the diff of docker-compose.yml:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 871e5d3..e06aacc 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,7 +6,7 @@ services:
     image: ghcr.io/seanmorley15/adventurelog-frontend:latest
     environment:
       - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
-      - ORIGIN=http://localhost:8080
+      - ORIGIN=http://100.64.32.40:8080
       - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
     ports:
       - "8080:3000"
@@ -35,9 +35,9 @@ services:
       - DJANGO_ADMIN_PASSWORD=admin
       - DJANGO_ADMIN_EMAIL=admin@example.com
       - PUBLIC_URL='http://localhost:81'
-      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app
+      - CSRF_TRUSTED_ORIGINS=http://100.64.32.40:8080
       - DEBUG=False
-      - FRONTEND_URL='http://localhost:8080'
+      - FRONTEND_URL='http://100.64.32.40:8080'
     ports:
       - "8000:8000"
     depends_on:
```

**Comment by NovaCyntax** [comment]
I will attempt this again tonight with a fresh Adventure Log configuration and follow the same steps that you did. This looks to be a 1:1 of the steps that I followed, but it's possible I missed something.

**Comment by NovaCyntax** [comment]
Using the docker-compose.yml example from the repo, I made the suggested changes. The only other things I changed were a couple port values, and a couple directory naming conventions. I still receive 403 errors attempting to login, and I have cleared my browser of all data from the site. Funnily enough, this is now occurring via my local IP address as well.

**docker-compose.yml** (censored Tailscale IP address using the example from above)

```
version: "3.9"

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
      - ORIGIN=http://100.64.32.40:8097
      - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
    ports:
      - "8097:3000"
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - /home/my-user/adventure-log/postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:81'
      - CSRF_TRUSTED_ORIGINS=https://100.64.32.40:8097
      - DEBUG=False
      - FRONTEND_URL='http://100.64.32.40:8097'
    ports:
      - "8567:8000"
    depends_on:
      - db
    volumes:
      - /home/my-user/adventure-log/media:/code/media/

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - /home/my-user/adventure-log/media:/app/media
      - /home/my-user/adventure-log/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

volumes:
  postgres_data:
  media:
```

**proxy/nginx.conf**
```
server {
    listen 80;
    server_name localhost;

    location /media/ {
        alias /app/media/;
    }
}
```

Thank you again for the detailed assistance

**Comment by tedski** [comment]
I copied your docker-compose.yml to a fresh install the same way I did in my previous attempt.  I replaced all instances of `my-user` with local user and all instances of the tailscale ip with my actual tailscale ip.  I was able to login with admin:admin as expected when navigating to `http://<tailscaleip>:8097/` where `<tailscaleip>` is the ip address I get from running `tailscale ip -4` on the vm that's hosting the docker containers.

**Comment by tedski** [comment]
As a side note, unrelated to this issue... if you're going to bind mount directories into your containers, you don't need the `volumes` section at the bottom of the docker-compose.yaml.  Those volumes go unused in your compose spec.

**Comment by NovaCyntax** [comment]
Yes, I'm thinking that this is a browser issue or something else. I will close the issue for now and diagnose some other moving parts. Thank you for the help!

**Comment by cubargh** [comment]
I'm getting the same 403 error btw

Here is my docker-compose.yml

```
version: "3.9"

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
      - ORIGIN=http://<tailscaleip>:9080
      - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
    ports:
      - "9080:3000" # yep, I changed the default IP
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:81'
      - CSRF_TRUSTED_ORIGINS=http://<tailscaleip>:9080,http://<tailscaledevicename>:9080
      - DEBUG=False
      - FRONTEND_URL='http://<tailscaleip>:9080'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - adventurelog_media:/app/media
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

volumes:
  postgres_data:
  adventurelog_media:
```

**Comment by tedski** [comment]
Which browser are you using?  I was testing on Chrome 127.0.6533.120.

**Comment by NovaCyntax** [comment]
I was using Firefox Stable.

**Comment by tedski** [comment]
Let me re-validate with firefox.

**Comment by tedski** [comment]
With Firefox 129.0.1 (64-bit) and all other steps the same as before, I have no issues logging in to the service over the Tailnet.

**Comment by brucejackson** [comment]
I struggled to get AdventureLog onto Tailscale and I would just like to add a sample docker-compose.yml that I ended up.  It took me a while to realize that both web and server needed to be proxied and accessibile to the end user.  It is based on [Contain your excitement: A deep dive into using Tailscale with Docker](https://tailscale.com/blog/docker-tailscale-guide).    

```
services:

  ts-adventurelog:
    image: tailscale/tailscale:latest
    container_name: ts-adventurelog
    hostname: adventurelog
    dns:
      - 127.0.0.1  # I found these DNS entries were needed to ensure that the container could create a HTTPS Certificate
      - 1.1.1.1
    environment:
      - TS_AUTHKEY=TAILSCALE_AUTH_KEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:travel
      - TS_SERVE_CONFIG=/config/adventurelog.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - "./ts-adventurelog/state:/var/lib/tailscale"
      - "./ts-adventurelog/config:/config"
      - "/dev/net/tun:/dev/net/tun"
      - "./Caddyfile:/app/Caddyfile"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=https://adventurelog.XXXXXXXX.ts.net:8443 # Tailscale proxies this to 127.0.0.1:8000
      - BODY_SIZE_LIMIT=Infinity
    network_mode: service:ts-adventurelog   # use network_mode instead of ports
    #ports:
    #  - "8015:3000"
    depends_on:
      - server
      - ts-adventurelog

  db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: CHANGE_ME
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=CHANGE_ME
      - SECRET_KEY=CHANGE_ME
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=CHANGE_ME
      - DJANGO_ADMIN_EMAIL=CHANGE_ME
      - PUBLIC_URL=https://adventurelog.XXXXXXXXXXX.ts.net:8443 # Port must be publicly accessible -  used for the creation of image urls.  Proxied to port 8000 by Tailscale serve
      - CSRF_TRUSTED_ORIGINS=https://adventurelog.XXXXXXXX.ts.net,https://adventurelog.XXXXXXXX.ts.net:8443,https://adventurelog.XXXXXXXX.ts.net:443,http://TAILSCALE_IP_ADDRESS  # Comma separated list of trusted origins for CSRF
      - DEBUG=True
      - FRONTEND_URL=https://adventurelog.XXXXXXXX.ts.net # Used for email generation. This should be the url of the frontend
      - EMAIL_BACKEND=email
      - EMAIL_HOST=CHANGE_ME
      - EMAIL_USE_TLS=true
      - EMAIL_PORT=587
      - EMAIL_USE_SSL=False
      - EMAIL_HOST_USER=CHANGE_ME
      - EMAIL_HOST_PASSWORD=CHANGE_ME
      - DEFAULT_FROM_EMAIL=CHANGE_ME
    #ports:
    #  - "8016:80"
    network_mode: service:ts-adventurelog  # use network_mode instead of ports    
    depends_on:
      - db
      - ts-adventurelog
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:

```

I then created a json file adventurelog.json to configure TailScale serve and funnel.  This creates 2 proxies.   Port 443 -> port 3000 and Port 8443 -> Port 8000.   This file is stored in `ts-adventurelog/config`.  I have Tailscale Funnel turned on.  It can be turned off in this file.  
```
{
  "TCP": {
    "443": {
      "HTTPS": true
    },
    "8443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:3000"
        }
      }
    },
    "${TS_CERT_DOMAIN}:8443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8000"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": true,
    "${TS_CERT_DOMAIN}:8443": true
  }
}
```
