### ISSUE TITLE
Enhancement: Full size image view

### ISSUE THREAD

**Issue by PhiCoderX** [seanmorley15/AdventureLog#243]
Great work seeing the picture carousel implemented!

One suggestion would be that clicking on an image opens a preview in the original aspect ratio on top of the current view. Pictures are being cropped to fit the landscape aspect ration which can loose important details from pictures in portrait format. It would be nice to see the original aspect ration without having to right click -> open in new tab.

**Comment by seanmorley15** [comment]
Gotcha, that would be a good idea. I will add this to get worked on!
Thanks!
