### ISSUE TITLE
Feature Request: Reformat/Redesign Transportation Card 

### ISSUE THREAD

**Issue by lovwyr** [seanmorley15/AdventureLog#252]
The Transportation Card in the Itinerary by Date View can be a bit overwhelming when the Locations are getting longer. 

Maybe add a line break after to or use a Table like Formatting

```
|From: | $from |
|To: | $to |
```

Further ideas: 

- Modify Date & Time to Start Date & Time
- Add End Date & Time 
- Autocalculate Duration if both are set and show the on the Card

![Bildschirmfoto_20240819_211509](https://github.com/user-attachments/assets/742f248b-6468-47fa-8fb7-a9254598f396)

**Comment by seanmorley15** [comment]
This is a good idea! I will work on this.

**Comment by seanmorley15** [comment]
How does this look?
![image](https://github.com/user-attachments/assets/a9e61e75-590c-4da9-ae14-e21952a0dd8e)

**Comment by lovwyr** [comment]
Looks great 😊

**Comment by seanmorley15** [comment]
Awesome! I will merge this to main!
