### ISSUE TITLE

Apply new logo to app

### ISSUE THREAD

**Issue by n00b12345** [seanmorley15/AdventureLog#298]
This repository contains icons that self hosters can use for their dashboards like homepage. Please consider adding an icon through a pull request for Adventure Log.

Link to dashboard icons repository - https://github.com/walkxcode/dashboard-icons

**Comment by seanmorley15** [comment]
Soo... Yes I totally agree, but this brings up a larger issue that I would like to address first. The AdventureLog icon is actually based on a design that I feel the rights to use are sketchy, basically I would like to be in full control of the AdventureLog brand and icon. (if you are on windows search for the map emoji!) I am going to rename this issue in hopes someone who as a creative mind can help create a new icon.

# New Icon Ideas
- Keep it close to the old logo while not being the old logo
- Image of map, possibly a pin on the map

## Formats
- A 512x512 png for the favicon.
- Any large formats / banners for displaying on things like the README.

Submit any ideas below,
Help and ideas is always appreciated!

**Comment by redtechtiger** [comment]
Here's a draft:
![AdventureLog](https://github.com/user-attachments/assets/89e00ee9-b74a-489d-94b0-bc1fdd32ea57)

**Comment by seanmorley15** [comment]
@redtechtiger This is amazing 🤩! Thanks so much!

**Comment by seanmorley15** [comment]
@n00b12345 I know this issue is closed but I made the pull request to dashboard icons https://github.com/walkxcode/dashboard-icons/pull/776
Thanks for the idea!

**Comment by seanmorley15** [comment]
The icon has been officially added to [walkxcode/dashboard-icons](https://github.com/walkxcode/dashboard-icons)!

**Comment by n00b12345** [comment]
> The icon has been officially added to [walkxcode/dashboard-icons](https://github.com/walkxcode/dashboard-icons)!

Yay! Thank you 😊

**Comment by redtechtiger** [comment]
@seanmorley15 Consider deleting the forked repository now that the PR has been merged. :)
