### ISSUE TITLE
A few suggestion to make self-hosting easier

### ISSUE THREAD

**Issue by n00b12345** [seanmorley15/AdventureLog#299]
### Discussed in https://github.com/seanmorley15/AdventureLog/discussions/296

<div type='discussions-op-text'>

<sup>Originally posted by **n00b12345** September  6, 2024</sup>
Thank you for making Adventure Log. I have got it running and it's beautiful.

1. Please consider including the "disable registration configuration" within the docker compose file as a commented out line
2. Please consider removing the "version" in the docker compose file (since it's deprecated, it throws a warning message)
3. Please consider elaborating a little bit on the lines that needs to be changed within the docker compose file (especially related to servers)

A lot of self hosted users (like me) aren't tech savvy, but would love to use something like this. So, making things a little easier for them would go a long way in helping them.</div>

One other suggestion which may not be immediately apparent to users:

Please consider adding to the documentation that postgres password in the docker compose should be the same as PG password. It's obvious, but it can be easily missed.

Thank you.

**Comment by n00b12345** [comment]
Another suggestion, please consider adding `restart: unless-stopped` to the docker compose.

**Comment by seanmorley15** [comment]
Good ideas! This has been added to the next milestone!
