### ISSUE TITLE
Automatic marking of a visited region while creating an adventure

### ISSUE THREAD

**Issue by dymek37** [seanmorley15/AdventureLog#306]
Hi,

I would like to suggest a new feature. Would it be possible to add an option to mark a region (administrative unit) as visited when creating a new adventure?

The idea would be as follows: in the location search field, I enter a name, and the system finds the appropriate location. After the search, information about the region to which the location belongs appears, along with a toggle to mark the region as visited.

Of course, this is just a suggestion, and I’m not sure if it’s feasible, but I believe it could be useful!

Thanks for considering my proposal!

**Comment by seanmorley15** [comment]
Hi!,
This is actually currently a feature, but is very limited. Currently, only a few countries like USA and Canada are supported. Currently it uses a lot of GeoJSON to determine region but this is limited and takes a lot of work to setup. I am looking for a dataset or external API that can take coordinates and return the region. AdventureLog already uses OpenStreetMap Nominatim so it would be cool if I could leverage that instead.
This will be worked on, thanks!

**Comment by dymek37** [comment]
It would be great if it could be done! I’m keeping my fingers crossed!

**Comment by tigattack** [comment]
Could the Nominatim reverse endpoint do what you need? Or perhaps the OSM Overpass API?

**Comment by seanmorley15** [comment]
After doing some testing, the Nominatim reverse geocoding should do the trick for the most part. Due to the fact that its not _always_ perfect, I will make it so it can prompt the user something like "Would you like to mark {region} as visited?" when they submit. The Nominatim API gives out the ISO codes that match what AdventureLog uses more times than not so this should be a cleaner and easier system.
I will work on this soon!

**Comment by seanmorley15** [comment]
Hi everyone! Just had some time to implement this today! It is in the beta branch for further testing (although from my testing it works very well!). It will be released as a part of the next update.
![image](https://github.com/user-attachments/assets/98f91658-6018-47d4-b66d-7d39923791b1)
Enjoy!

Also, any feedback or tweaks are welcome :)
