### ISSUE TITLE
[FEATURE REQUEST] Translation logic

### ISSUE THREAD

**Issue by lukasitaly** [seanmorley15/AdventureLog#312]
If you can incorporate the translation logic, I would be happy to translate everything into Italian and German. 

Personally, I don't need something like Weblate, a simple JSON file with the strings is good enough.

**Comment by dymek37** [comment]
I can translate to Polish.

**Comment by valentin8709** [comment]
Yep good request, I can translate to french.

**Comment by seanmorley15** [comment]
Great idea, I plan to implement this with `svelte-i18n`. I will get the English translation file done first then anyone who wants to help can take that file and translate!
Thanks for the willingness to help!

**Comment by seanmorley15** [comment]
Hi everyone! I just finished moving AdventureLog to a localization framework and have generated some localization files using a google translate API. These files can be found here; https://github.com/seanmorley15/AdventureLog/tree/development/frontend/src/locales. If you can, take a look at some of them to check their accuracy or make a PR for a new one! The English file (en.json) serves as the main file that the others should be based off of. Thanks so much for the help!
