### ISSUE TITLE
Separate adventure/collection status from type.

### ISSUE THREAD

**Issue by AadNL** [seanmorley15/AdventureLog#313]
Separate adventure/collection status (visited/planned) from adventure types (dining/lodging). 
Make status available in adventure and collection (with - option to have - collection status forcing/hiding included adventure status).

**Comment by seanmorley15** [comment]
This issue is worked on currently!

**Comment by seanmorley15** [comment]
Hey @AadNL, in issue #292, I am working on moving away from types like visited/planned to categories. This allows for more flexibility when creating an adventure. I could also add the categories to collections themselves, or have the collections show the types of categories inside them. I will close this issue to prevent duplicates but rest assured its being working on for the next update!
Thanks!
