### ISSUE TITLE
[BUG] remove link url length restriction

### ISSUE THREAD

**Issue by Snuupy** [seanmorley15/AdventureLog#317]
**Describe the bug**

After creating an adventure, I'm trying to add a google maps link for my car drive routing to the link section. The link is very long, and I don't want to create a short link every time because I frequently add/update my route depending on changes. However, when putting this long link in the field and updating the adventure, I get an error. On shorter links it works fine. This is probably due to postgres type varchar instead of a string or whatever

**To Reproduce**
1. Try going to maps.google.com and adding 10 stops along the route, then click "Copy Link". It's very long.
2.  Put the link in the `Link` field in an adventure
3. submit
4. see error

**Expected behavior**

it should accept links of arbitrary length

**Screenshots**

![image](https://github.com/user-attachments/assets/e9d2c944-80e4-4ba2-b8e8-d923467ca10e)

**Docker Compose**
If the issue is related to deployment and docker, please post an **obfuscated** (remove secrets and confidential information) version of your compose file.

**Additional context**

**Comment by seanmorley15** [comment]
All set in the recent commit. The old max length for the URLs was 100 now its set to the standard limit of 2,083 characters. There is also now better error handling for this and it will show up in the modal itself. In addition, long URLs will be truncated in the details view page so they do not look bad.
Thanks for reporting this, enjoy!
