### ISSUE TITLE
[BUG] Adventures details cannot be accessed if collection is shared to more than one person

### ISSUE THREAD

**Issue by Afaren57** [seanmorley15/AdventureLog#321]
**Describe the bug**
Today, I tried to look at a collection I was working on since the last error with the db and I could not open any adventure. Every adventure within a collection has a problem and can't be opened while the only one I have outside of a collection doesn't. This one can be opened but the other cannot.

Here is the log of the server when trying to open one adventure inside a collection:

```
Internal Server Error: /api/adventures/02d131fd-da05-4e4c-8be4-f90d271d63f0/

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper

    return view_func(request, *args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/code/adventures/views.py", line 95, in retrieve

    adventure = get_object_or_404(queryset, pk=kwargs['pk'])

  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 86, in get_object_or_404

    return queryset.get(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 652, in get

    raise self.model.MultipleObjectsReturned(

adventures.models.Adventure.MultipleObjectsReturned: get() returned more than one Adventure -- it returned 2!

"GET /api/adventures/02d131fd-da05-4e4c-8be4-f90d271d63f0/ HTTP/1.1" 500 145
```

It looks like somehow they were duplicated, thus the backend send an error.

**To Reproduce**
1. Have an adventure inside a collection
2. Try to open it

**Expected behavior**
Should open the adventure

**Screenshots**
![Screenshot_20240927-123349](https://github.com/user-attachments/assets/bd435892-f37f-4187-bd18-755b49c7875e)

**Docker Compose**
N/A

**Additional context**
I don't know if this is important but the collections were shared with other users

**Comment by seanmorley15** [comment]
Hey @Afaren57, I just ran through the steps of preproducing this and was unable, including using the bad update and fix. I wonder if you tried and restore your database somehow because there are most likely duplicated adventures with the same primary key. If its not too many, you can go into the admin site (server url `/admin`) and click adventures. Then remove duplicates ones there instead. I Am curious because I have never seen this before.
Sorry this happened,
Keep me posted!

**Comment by Afaren57** [comment]
After the previous bug I had with the db and the fix you gave me, I just populated the collection for my next trip and that's it. Today, I shared it with someone in my server and when I checked an item in it, I saw it couldn't load any adventure. Thought it could be due to the shar but another collection also had the problem and it wasn't the case for adventures outside collections.

Anyway, I will try going to the admin panel to check this. I'll tell you if I could fix it :)

**Comment by Afaren57** [comment]
That was fast, the /admin page returns 404: not found error…

**Comment by seanmorley15** [comment]
Are you doing '/admin' on the server container?

**Comment by Afaren57** [comment]
I tried my frontend adress followed by /admin, eg.: https://frontend-adventurelog.domain.tld/admin
Is that not how you get to it ? Sorry if I'm dumb on this one ^^'

**Comment by seanmorley15** [comment]
So its should be what ever you api server is /admin so for example
`https://api.adventurelog.app/admin`

**Comment by Afaren57** [comment]
Oh, yeah, dumb me forgot about it, checking it now :)

**Comment by Afaren57** [comment]
When I look into the adventures section, I see only one item of each adventures I have in my app…

**Comment by seanmorley15** [comment]
Ok that's fine, Django admin probably is hiding them because they should not be there,
I just got this command, **I have not tested it and I will later so it could cause data loss, i'm not sure**
`DELETE FROM adventures_adventure WHERE id IN (SELECT id FROM (SELECT id, ROW_NUMBER() OVER (PARTITION BY id ORDER BY id) AS row_num FROM adventures_adventure) AS duplicates WHERE row_num > 1);`
This supposedly will remove all duplicate id's in the adventure table when you run it after accessing `python manage.py dbshell`

If you were going to do this definitely back up your database but I will try it later too

**Comment by Afaren57** [comment]
It deleted 0 item, bug is still happening :/

**Comment by seanmorley15** [comment]
This is very confusing and I don't know why this would even happen in the first place. I will try this weekend to mess around with it   but I went through the whole list of steps (even sharing and different collections) and even changed app versions without creating this. This is the _joy of selfhosting_, random things happen at random times!
Sorry for any confusion and I hope to help you get this working soon!

**Comment by Afaren57** [comment]
yeah, shit happens as they says x)
I don't know why it started to happen too, hopefully you'll find somthing ^^
GL :)

**Comment by Afaren57** [comment]
OK, after some testing, it seems that sharing to 2 people breaks it. Unsharing to one unbreaks it.

**Comment by seanmorley15** [comment]
Thanks so much for this information, I will fix this very soon!

**Comment by seanmorley15** [comment]
I can **confirm** this is a bug. A fix is in progress. I would not have found this without @Afaren57!

**Comment by seanmorley15** [comment]
All set! If you want to test the fix you can checkout the `sharing_fix` branch. The issue actually had nothing to do with the database and was just the way the API was fetching objects that was problematic.
I am very cautious and taking my time to test thoroughly before merging into main, it should be done in the next few days. I will close this issue when that's complete.
Thanks so much for bearing with me and i'm glad we got to the bottom of this!

**Comment by Afaren57** [comment]
I will try this branch to test the fix, should I just change the server version in my docker compose or every latest tags ?

**Comment by seanmorley15** [comment]
Don't worry about testing it because it involves building your own docker image. I will take care of making sure it works and when it's done I'll let you know so you can pull the latest image.
