### ISSUE TITLE
[BUG] Unable to start/install the docker system

### ISSUE THREAD

**Issue by pippo73** [seanmorley15/AdventureLog#351]
**Describe the bug**
I'm trying to do a fresh install of the system

**To Reproduce**
1. on a working docker system
2. run the command `wget https://raw.githubusercontent.com/seanmorley15/AdventureLog/main/docker-compose.yml`
3. run the command `docker compose up -d`

**Expected behavior**
the system should start as expected

**Docker Compose**

I've used the original file before doing any modifications

**Additional context**

here is the error I get instead of the running system

```
$ docker compose up -d
[+] Running 4/5
 ✔ Network adventure_default        Created                                                                                                              0.1s
 ✔ Container adventurelog-db        Started                                                                                                             27.5s
 ✔ Container adventurelog-backend   Started                                                                                                             21.0s
 ⠼ Container adventurelog-nginx     Starting                                                                                                            11.8s
 ✔ Container adventurelog-frontend  Started                                                                                                             11.1s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pippo/Adventure/proxy/nginx.conf" to rootfs at "/etc/nginx/conf.d/default.conf": create mount destination for /etc/nginx/conf.d/default.conf mount: cannot mkdir in /var/lib/docker/overlay2/b90e775451852d90c46f7e2397a439b7f956545655d56aeac92923daa1930230/merged/etc/nginx/conf.d/default.conf: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```

**Comment by pippo73** [comment]
ok, 
I've discovered that the problem was the missing file of nginx.
Now I've started it, but I still cannot signup to the server :-( any idea?

**Comment by seanmorley15** [comment]
Hi @pippo73, I would check your `ORIGIN` variable on the frontend. Make sure that you are accessing the app from that URL. The 200 code in the request you provided means that the connection from the frontend to the backend is most likely not an issue.
Keep me updated!

**Comment by pippo73** [comment]
I've changed the variable with the ip of my server and now it works. Thank you

**Comment by pippo73** [comment]
Thanks for the support
