### ISSUE TITLE
[REQUEST] Allow opening an adventure from within the map

### ISSUE THREAD

**Issue by MrColumbo** [seanmorley15/AdventureLog#357]
If you use the map to for example check the closest adventure based on your current location you are able to see the title by clicking on the marker but it looks like there is no way to open the adventure to see all the details

**Comment by seanmorley15** [comment]
![image](https://github.com/user-attachments/assets/0b829ec1-2aac-45e4-bf68-ba632c2342d3)
All set for the next update!
