### ISSUE TITLE
[REQUEST] show thumbnail when clicking on marker

### ISSUE THREAD

**Issue by MrColumbo** [seanmorley15/AdventureLog#358]
since there is the ability from the very beginning from this app to use images to make everything a bit more visual it will be a nice improvement if thumbnails will be also shown on the map (maybe after clicking on the marker)

**Comment by seanmorley15** [comment]
All set in development! Thanks!
![image](https://github.com/user-attachments/assets/19d70339-1fae-4840-aeb2-02b88e105393)
