### ISSUE TITLE
[REQUEST] use activity type icon insead or that blue symbol on map

### ISSUE THREAD

**Issue by MrColumbo** [seanmorley15/AdventureLog#359]
I think it is quite nice to be able to select the type of activity but it will be even better to visualize that on the map. Instead of using the blue marker for everything it will be nice to use the icon of the type of activity.

**Comment by seanmorley15** [comment]
Working on this right now! Really cool idea!!
![image](https://github.com/user-attachments/assets/fb302e10-18f6-485e-b6d8-ed490b875281)
