### ISSUE TITLE
[REQUEST] Share Collections with other users.

### ISSUE THREAD

**Issue by ozhound** [seanmorley15/AdventureLog#368]
I'd like to be able to share a trip / collection with another user so that they can see the itinerary, but not have the whole thing "public" as my instance is externally accessible so I can add information whilst on the road. Perhaps different permission levels could be established so that different users can contribute to the trip (photos, updates etc)

I'd like to take the opportunity to say how impressed I am at the ease of installation and use of the software. I've used a few public ones, and they certainly have addition features over AdventureLog, but I can see that you are adding features, and it doesn't cost anything (and my data is stored on my own server) Well Done!

**Comment by seanmorley15** [comment]
Hi @ozhound, I think what you are describing is already a feature! On the collection card, click the `...` button then click share. It will open a popup with a list of users on your server that have their profile **set as public**. Once shared, these users can click on their profile, then `Shared With Me` to view the collection you shared with them. They can then collaborate on the itinerary with you!
Let me know if this answers your question!

**Comment by ozhound** [comment]
Ahh yes, seems that this is what I was asking for. Thankyou

**Comment by Vercety87** [comment]
Hi @seanmorley15 it would be convenient to display collections shared with me on my “Collections” tab. Is it something you could add in a future version ? Thanks.

**Comment by seanmorley15** [comment]
> Hi @seanmorley15 it would be convenient to display collections shared with me on my “Collections” tab. Is it something you could add in a future version ? Thanks.

Yes! I could make it easier to view the ones shared with you. I will probably combine the "shared with me" tab as a subset of the collections page. I'll work on this 😀
