### ISSUE TITLE
[BUG] Broken site view. Doesn`t work Bootstrap correctly and no images country flag

### ISSUE THREAD

**Issue by obetsa** [seanmorley15/AdventureLog#369]
**Describe the bug**
Doesnt work Bootstrap correctly and no images
for images  with country flag using:
`python manage.py download-countries`   -  in container console

**Screenshots**
![photo_2024-11-20_11-11-12](https://github.com/user-attachments/assets/0270b9be-d28d-47e4-9bfa-39cc7a8ef0cc)
![photo_2024-11-20_11-11-18](https://github.com/user-attachments/assets/415e9a86-6b56-4e97-a8d1-e7e269b81498)

**Docker Compose**
Work with synology  nas station
Here is my yaml file taken from mariushosting

```
services:
  db:
    image: postgis/postgis:16-master
    container_name: adventurelog-DB
    hostname: adventurelog-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "adventurelog", "-U", "adventureloguser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/adventurelog/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    restart: on-failure:5

  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-FRONTEND
    environment:
      - PUBLIC_SERVER_URL=http://server:8000
      - ORIGIN=https://adventurelog.myname.synology.me
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - 9866:3000
    depends_on:
      - server
      
  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: AdventureLog-SERVER
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - DISABLE_REGISTRATION=false
      - PUBLIC_URL=https://adventurelogapi.myname.synology.me
      - CSRF_TRUSTED_ORIGINS=https://adventurelog.myname.synology.me
      - DEBUG=False
      - FRONTEND_URL=https://adventurelog.myname.synology.me
    ports:
      - 8669:80
    depends_on:
      - db
    volumes:
      - /volume1/docker/adventurelog/media:/code/media:rw
```

**Additional context**
Looking for th previous closed issues this code shoud work. 
i will be glad that you looking this issue

**Comment by seanmorley15** [comment]
Hi @obetsa, the issue with the translation error is confusing me, I have never seen that other than when I was developing. Are you able to check the browser logs and see if there is anything there to show? Thanks!
Once this is fixed I'll assist with the images, I want to get this fixed first

**Comment by obetsa** [comment]
@seanmorley15 yes, i checked browser logs before writing here. Here is some screenshots, that shows there are no any errors in network field. But in the Element area, button class looks strange, like something did not work correctly.
ok. also i check url in others browsers, take another pc, recreate containers - its the same problem. I do not using nginx. Or maybe some ports must be opened to word, but i dont think so.
![Screenshot 2024-11-20 162818](https://github.com/user-attachments/assets/bb61e03e-153e-476e-98b3-a5479658c07c)
![Screenshot 2024-11-20 162905](https://github.com/user-attachments/assets/faba7715-8eb7-4b3b-b98d-46129e9c6bf2)

**Comment by seanmorley15** [comment]
@obetsa, this is weird! I checked my version and on the elements tab I see the proper text like this.
![image](https://github.com/user-attachments/assets/17b2633f-d66e-419d-b0e9-bc33df61cfa3)
I wonder if this is somehow and SSR error, can you check the logs of the frontend container?? Also what browser are you using?
Thanks and sorry this is happening, this is a weird one for sure!

**Comment by seanmorley15** [comment]
WAIT FOUND IT!!!! I found the issue is when using an unsupported locale on your browser, try changing manually to a language using the 3 dots dropdown for now. This is a bug i will fix ASAP

**Comment by obetsa** [comment]
@seanmorley15 cool. i changed locale as you said and its help. Thank you!
i may ask you to add Ukraine locale, as you can. Thanks also.

About image.  The code show that there are no images, but they are located in the server in the source path. Maybe it is a problem with permission to folder media(where are image located). The url from` img src` show Forbidden page 403.
I try to check it later for permission or maybe looking to open some ports.
![Screenshot 2024-11-20 172914](https://github.com/user-attachments/assets/68474a5b-4691-45d3-adfa-c056123d7858)

**Comment by seanmorley15** [comment]
@obetsa, I will add the Ukraine locale next! Regarding the images and the 403 error this info from someone in the community discord server might help -  I guess it has something to do with my CSRF_TRUSTED_ORIGINS. I always had it set to https://travelapi.mydomain.com/ when I changed it to http://travelapi.mydomain.com/ it works. Also visiting the https://travelapi.mydomain.com/flags/af.png did not work before, which does now. So I am not quite sure if this was the solution, however it helped in my case.

**Comment by obetsa** [comment]
For my case, the solution for visibility images was to give the permission **rw** for everyone to folder (../media/..).(thanks mariushosting for help)
for CSRF_TRUSTED_ORIGINS it is enough to add the same url as in ORIGIN with https. 
but now, you need to know that all photos or images that you post will be visible in intenet!
Thanks @seanmorley15 for help, and waiting and hope that you add ukraine locale soon.
now can close issue

**Comment by seanmorley15** [comment]
Hi @obetsa, glad its working now! Is there a reason to reopen the issue? I want to make sure everything is all set before closing

**Comment by obetsa** [comment]
sorry my bad, smth like miss clik. everything for my case **working correctly** 
add some info for my previous comment:
in CSRF_TRUSTED_ORIGINS it is needed to add ORIGIN and also PUBLIC_URL with https by comma separated if you want django admin page work correctly.. but maybe it is only for my case.
