### ISSUE TITLE
[REQUEST] Filter Adventures in Collection Page

### ISSUE THREAD

**Issue by seanmorley15** [seanmorley15/AdventureLog#370]
**Describe the solution you'd like**
Be able to filter within a collection itinerary view like you can for the adventure view.
Possibly be able to toggle between a card view and the itinerary view?
Could include a general overhaul of the itinerary page to make it more clean and visually appealing.

**Comment by nebriv** [comment]
Being able to filter on the tags and categories would be awesome as well. We've been adding potential POIs to a collection and it gets a little messy trying to sort out which are potentials and which are actual things we want to do. I think a "global" filter at the top would be a good fit, this would apply to linked adventures as well as transportations/notes/itinerary. That would allow you to quickly filter things in/out. "Show me all the restaurants we have picked out" kind of thing and then you could see oh, hey we're missing a day that we never picked out a restaurant. 

Shrinking the icons or providing a toggle for icon vs list view would help clean up the Collection Page as well. Another thing that we thought might be useful would be to include a partial of the description on the adventure card so you can briefly see what it is without opening the card. Just something to better utilize the empty space.

Idea for the itinerary page would be to have some sort of calendar view, Anything more than a few days requires quite a bit of scrolling currently.

**Comment by seanmorley15** [comment]
I am working on this right now but have a few questions / things I could do along the way:
1. Should I keep the list of all linked adventures, transportations, etc at the top of the collection page?
2. Should the itinerary date view stay pretty much the same?
![image](https://github.com/user-attachments/assets/6887ddbf-ab22-4f0b-89c0-8b1007f6b60d)
3. I can also add a calendar view to show the collection as a calendar
4. Should I add a way to see what items are not already added to the date / itinerary planner?

**Comment by nebriv** [comment]
> Should I keep the list of all linked adventures, transportation, etc at the top of the collection page?

I think so, perhaps just as a list (or smaller boxes) though? It does take up a lot of space visually. Or perhaps only adventures that are not added to the itinerary? Split the difference and add a toggle "Show/Hide Scheduled Adventures"? I do think keeping the transportation and notes at least grouped together visually separates it out nicely. i.e. "These are my flights", "these are my notes".

> I can also add a calendar view to show the collection as a calendar

A calendar view would be very helpful - I personally would prefer it. Anything more than a few days gets long to scroll through. 

Another note that we ran into during a planning session - our dates were off by one with the day counter. So we had February 4th and it was on the "3rd" day of the trip. This ended up being a little confusing visually at least. I think the calendar view would go a long ways towards that as well.

Also on the flight cards, one way I was thinking it could be tightened up a bit would be to move the start and end dates in line with the origin/destination. This would make sense logically as thats generally how people are used to seeing their flights (I leave from JFK at 9:25PM, and get into COS at 9:25PM)

**Comment by seanmorley15** [comment]
Sounds good, thanks!
I will make a toggle at the top to show/hide included items as well as make the global card view smaller and possibly even a list view.
Regarding the "off by one" with the dates, I will look into this further but the server only stores dates as UTC then uses the browser to turn them into locale dates... so there might be some issue here that I will do some testing for.

**Comment by nebriv** [comment]
Oh just to be clear the date was 💯 correct. Not a true off by one luckily 😛

It just happened to be "day 3" where as the actual date was the 4th. So it took a second glance of like wait is this the 4th day or the 3rd day. I think just having the day number and date next to each led to some confusion?

**Comment by seanmorley15** [comment]
Ohh ok I understand. I will try and make both the day number and date more clear!

**Comment by seanmorley15** [comment]
Super excited to share this update! I rewrote editing modals for transportations, notes, and checklists as well as overhauled the collection page with markdown support and a calendar. The "all items" view also shows what items have dates out of range of the collection for better organization. Here are some screenshots!
![image](https://github.com/user-attachments/assets/feaf9a29-164e-4677-b5ed-6f8d79976c04)
![image](https://github.com/user-attachments/assets/506d2787-e9ac-492b-b9da-553d203d5558)
![image](https://github.com/user-attachments/assets/236e1b04-053c-4b76-b7e4-66ab60525dee)
![image](https://github.com/user-attachments/assets/4750fb74-6e95-435a-846a-14afd65f38fa)
![image](https://github.com/user-attachments/assets/4f9ab356-5a74-4701-b284-ced77802dd06)
![image](https://github.com/user-attachments/assets/c70456f0-12a0-4fb8-bead-f950b9706d53)
![image](https://github.com/user-attachments/assets/a72bbf43-8370-4eb2-94c2-8980ad32ef38)
