### ISSUE TITLE
[BUG] No default locale selected

### ISSUE THREAD

**Issue by Freika** [seanmorley15/AdventureLog#385]
**Describe the bug**
<img width="1720" alt="изображение" src="https://github.com/user-attachments/assets/051b9a20-9c23-4919-84f9-e3b68ed4108f">

**To Reproduce**
1. Open the https://adventurelog.app/login in anonymous tab

**Expected behavior**
<img width="1727" alt="изображение" src="https://github.com/user-attachments/assets/fa3f2328-9e92-4e43-b3c3-238902010bf6">

---

Great software by the way!

**Comment by dymek37** [comment]
s this the same as in the screenshot? In Docker, I’m using the latest tag for the image, and it seems like something has been updated (via Watchtower) even though I have the latest available version installed.
![obraz](https://github.com/user-attachments/assets/6d0c757f-b36b-4bd0-85a9-6e9992803d3d)

**Comment by dymek37** [comment]
Thanks for your quick help :)

**Comment by seanmorley15** [comment]
Docker images is building right now, should be ready in 15 min or so on the `latest` tag. Fixed by #376

**Comment by Freika** [comment]
Superfast! 🚀
