### ISSUE TITLE
[BUG] Can not navigate webpage after visiting a collection

### ISSUE THREAD

**Issue by SerinitySW** [seanmorley15/AdventureLog#390]
**Describe the bug**
The web page simply stops responding. The URI is changed when clicking on buttons, but it does not actually navigate. Doing a hard refresh (Ctrl + Shift + R) is the only way to get it to respond again and load the new URI's content.

**To Reproduce**
1. Add adventures, in this case I added 4
2. Create a new collection
3. Add all 4 adventures to the collection
4. Navigate to the collection by going to the collection tab at the top, and clicking on the title of the collection

**Expected behavior**
The web page should respond when trying to navigate away from it

**Screenshots**
![image](https://github.com/user-attachments/assets/3a330412-c6e5-4c91-be0e-e6555e37938d)
![image](https://github.com/user-attachments/assets/693e001f-c49e-426e-ba87-df36a17d5f5d)
![image](https://github.com/user-attachments/assets/7229e3d2-fc12-43d8-b6da-5b65d886b9bb)

**Docker Compose**
```
services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NOT NEED TO CHANGE THIS EVER EVEN IF YOU CHANGE THE OUTWARD PORT
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8015:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: censored
    volumes:
      - /mnt/user/appdata/AdventureLog/db/:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=censored
      - SECRET_KEY=censored
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='https://adventure-backend.domain.tld' # Match the outward port, used for the creation of image urls
      - CSRF_TRUSTED_ORIGINS=http://localhost:8016,https://adventure.domain.tld:443,http://192.168.10.40:8016,http://hostname.localdomain.tld:8016,http://hostname:8016,http://localhost:8015,http://adventure.domain.tld:80,http://192.168.10.40:8015,http://hostname.localdomain.tld:8015,http://hostname:8015,http://192.168.10.10:80,http://192.168.10.10:8080,http://192.168.10.10:443,http://proxyhostname.localdomain.tld:80,http://proxyhostname.localdomain.tld:8080,http://proxyhostname.localdomain.tld:443,,http://adventure.domain.tld:8080,https://login.domain.tld:43,http://localhost:8015,https://adventure.domain.tld,http://adventure.domain.tld,https://adventure-backend.domain.tld,http://adventure-backend.domain.tld # Comma separated list of trusted origins for CSRF
      - DEBUG=False
      - FRONTEND_URL='https://adventure.domain.tld' # Used for email generation. This should be the url of the frontend
    ports:
      - "8016:80"
    depends_on:
      - db
    volumes:
      - /mnt/user/userdata/AdventureLog/media/:/code/media/
```

**Additional context**
Thank you for this project, I've been wanting something like it for a long time :)

**Comment by seanmorley15** [comment]
Hi @SerinitySW! I just found and fixed a bug that I think was causing the issue you reported. The docker images are building right now and should should be done in like 10 minutes. Once ready, `docker compose pull` before you `docker compose up -d` to get the latest image from the `latest` tag.
Thanks for making this report very well structured, it allowed me to find the issue very quicky!

**Comment by matze939939** [comment]
Same issue here and fixed by pulling the new image. Thanks a lot!

**Comment by seanmorley15** [comment]
Glad to hear the fix works!
