### ISSUE TITLE
[REQUEST] Export and Sync to Calendar

### ISSUE THREAD

**Issue by MaximUltimatum** [seanmorley15/AdventureLog#396]
**Is your feature request related to a problem? Please describe.**
One of Adventure log's stated roles is for planning adventures.
As an adventurer, after I plan out a number of visits to various adventures, I would like to be able to share that adventure itinerary with other people going on the trip, without forcing them to use my homelab hosted apps.

**Describe the solution you'd like**
I view the solution to involve three levels of depth depending on feasibility and resources: 
1. A simple "export to iCalendar (or other open source standard most calendars can import from)" button on adventures and adventure collections. AdventureLog scrapes future (or all) trips from the database and gives the user a file to download. 

2. Support for directly exporting to a few common calendars. This gets exponentially more difficult the more kinds of calendars supported. So does maintenance. An easy out for this would be to support companies that make integration easy/FOSS-ish, and maybe 1 or 2 dominant players (Google Cal, Apple calendar) 

3. Support for syncing between common calendars and Adventure Log. That is; when the event is moved in the external calendar, the corresponding trip changes. When notes are added, they show up in the trip.

**Describe alternatives you've considered**
Present alternatives are copying the data over manually and just sharing adventure log with everyone who is going.

**Additional context**
As a bonus, providing a way to exfiltrate data from the app to a calendar let's us outsource other gnarly problems (reminders, navigation, etc) in a way that users still receive benefits from AdventureLog planning and presentation.

If I have some time over the holidays I can definitely work on at least level 1 compatibility!

**Comment by seanmorley15** [comment]
Your timing for this is right on, I was just searching for calendar libraries to add to the web app! In addition to doing the things you described, I can see having an integrated calendar that I can add to the new dashboard page I am making.
Thanks for this!
