### ISSUE TITLE
[REQUEST] Add Database for Airports

### ISSUE THREAD

**Issue by PascalBru** [seanmorley15/AdventureLog#397]
When adding a flight to a collection it would be perfect to use the IATA Airport Codes as a Location. 

A possible list of Airports could be used from https://github.com/mwgg/Airports

**Comment by seanmorley15** [comment]
This is an amazing idea! The dataset looks perfect for what I would need too.
This will be added to the roadmap!

**Comment by nebriv** [comment]
Maybe a further down the road enhancement that would be interesting would be to auto populate flight information based on flight number? That way I don't need to manually transcribe (and possibly introduce errors) if I don't want to. It would have to be API driven, so the instance admin would need to register and add an API key in from one of the various data aggregators:

Couple options I've found:
https://aviationstack.com/
https://airlabs.co/docs/routes
https://www.flightaware.com/commercial/aeroapi/#compare-plans-section

**Comment by seanmorley15** [comment]
That's an amazing idea! I would agree that expanding flight / transportation capabilities could be a big help for a lot of people. I will take a look at these API services!
