### ISSUE TITLE
[REQUEST] Add support for markdown to collection notes

### ISSUE THREAD

**Issue by nebriv** [seanmorley15/AdventureLog#401]
**Is your feature request related to a problem? Please describe.**
Current plain text is fine, but some basic formatting would allow me to convert my trip notes from another system (google Keep - don't ask..) into the collection.

I like to jot down daily notes in my travels, for example:
![510-360-max](https://github.com/user-attachments/assets/1a865434-28ae-4c62-82eb-cd834161cae7)

**Describe the solution you'd like**
Markdown support would add some flair to the notes and allow for better structured texts. Simple markdown for now would be excellent. This would also probably require a read vs edit view for notes.

**Comment by seanmorley15** [comment]
I will look into integrating it with a package like [https://github.com/BearToCode/carta](https://github.com/BearToCode/carta)
I agree with would help make the notes more useful!
