### ISSUE TITLE
[BUG] Category Icons - Required Icon but no ability to add icon on desktop, fails to save category

### ISSUE THREAD

**Issue by nebriv** [seanmorley15/AdventureLog#402]
**Describe the bug**
During the creation/edit of an adventure and while using the site on a desktop web browser the user is presented with the ability to add a category to an adventure. If a label is added, but no icon the adventure fails to save (See screenshot in screenshots). The icon field is simply a text field and does not provide any way to actually add an actual icon.  This results in the user having to enter text which is not rendered well:
![image](https://github.com/user-attachments/assets/fa42df08-cbbd-4079-aa81-351144880201)

**To Reproduce**
1. Create or edit an adventure, 
2. Add a new category and leave the "Icon" field blank.
3. Submit adventure.

**Expected behavior**

Ideally a pick list of emojis would be available.
Alternatively some sort of funny text matching with font awesome?

**Screenshots**
![image](https://github.com/user-attachments/assets/32deeb11-b1b6-444f-826f-98516ea1b132)

**Comment by seanmorley15** [comment]
Thanks for reporting this! I am going to try and find an emoji picker GUI so that when the user clicks on the icon field and is presented with something like this:
![image](https://github.com/user-attachments/assets/ab527488-69a2-4bce-ba6b-014cd4d26556)
I will make sure this is fixed for the next update this month.
Thanks!

**Comment by nebriv** [comment]
> Thanks for reporting this! I am going to try and find an emoji picker GUI so that when the user clicks on the icon field and is presented with something like this: ![image](https://private-user-images.githubusercontent.com/98704938/393656806-ab527488-69a2-4bce-ba6b-014cd4d26556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDQ2NjYsIm5iZiI6MTczMzcwNDM2NiwicGF0aCI6Ii85ODcwNDkzOC8zOTM2NTY4MDYtYWI1Mjc0ODgtNjlhMi00YmNlLWJhNmItMDE0Y2Q0ZDI2NTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAwMzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYjg4NGMyN2IyODczZmYxZmJmYmZhMDg2NzcyNzljMGI0MmUxNmZjY2Q0ZjM0M2ZjNDU5YTdmMDIwYmEyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.orYfYWJLl3BE1-RX99cNPRwBYzVfHsGYW7pSykqlQws) I will make sure this is fixed for the next update this month. Thanks!

Emoji picker is exactly what I was thinking!

**Comment by seanmorley15** [comment]
Emoji picker is looking good!
![image](https://github.com/user-attachments/assets/12be9559-adc1-4cb9-b1f9-567cea3fd545)
This will be released soon!
