### ISSUE TITLE
[DEPLOYMENT] fetching docker images is denied

### ISSUE THREAD

**Issue by recumbentbirder** [seanmorley15/AdventureLog#405]
## Explain your issue

I get `Error response from daemon: Head "https://ghcr.io/v2/seanmorley15/adventurelog-frontend/manifests/latest": denied: denied` for server, web, and db.

## Provide an **obfuscated** `docker-compose.yml`

Using the one pulled according to docker installation manual.

## Provide any necessary logs from the containers and browser

```
> docker compose up                                                                       
[+] Running 3/3
 ✘ server Error Head "https://ghcr.io/v2/seanmorley15/adventurelog-frontend/manifests/latest": denied: ...               0.6s 
 ✘ web Error    Head "https://ghcr.io/v2/seanmorley15/adventurelog-frontend/manifests/latest": denied: den...            0.6s 
 ✘ db Error     Head "https://ghcr.io/v2/seanmorley15/adventurelog-frontend/manifests/latest": denied: deni...           0.6s 
Error response from daemon: Head "https://ghcr.io/v2/seanmorley15/adventurelog-frontend/manifests/latest": denied: denied
```

**Comment by seanmorley15** [comment]
Hi!
I would try running `docker logout ghcr.io` to reset your docker credential status for GHCR and pull the image logged out. Both the frontend and backend images are public so they should not require any auth to pull. Try this and let me know how it goes!

**Comment by recumbentbirder** [comment]
Ohhh, that was embarrassing. Yes, it works. Thanks a lot!!!

**Comment by seanmorley15** [comment]
No problem! Glad its working :)
