### ISSUE TITLE
Add support for ultrawide resolutions

### ISSUE THREAD

**Issue by redtechtiger** [seanmorley15/AdventureLog#80]
### Description:
Pretty much the title: make the UI scale to bigger ultrawide monitors as well as HiDPI monitors!

### Severity:
Very low, I assume this only affects a very small % of users.

_Also yeah I still need more contribution points :)_

**Comment by seanmorley15** [comment]
![image](https://github.com/seanmorley15/AdventureLog/assets/98704938/9bc97d36-7f22-48b4-a4f2-3bf02faee9ac)

**Comment by seanmorley15** [comment]
Should be all set now!
